# yaml-language-server: $schema=./router_config_options.yaml
# yaml-language-server_if_online: $schema=https://raw.githubusercontent.com/wundergraph/cosmo/main/router/pkg/config/config.schema.json

version: '1'

dev_mode: true
log_level: debug


access_logs:
  enabled: true

telemetry:
  service_name: "cosmo-router"
  tracing:
    enabled: true
    export_graphql_variables: true
    propagation:
      jaeger: true
#      trace_context: true
    exporters:
      - endpoint: http://192.168.1.41:4317
        exporter: grpc


execution_config:
  file:
    path: "/router.json"

# websocket:
#   enabled: true 
#   forward_upgrade_headers: 
#     enabled: true

 
headers:
  all: # Header rules for all origin requests.
    request:
      - op: "propagate"
        named: "user-id"
      - op: "propagate"
        named: "Authorization"
      # - op: "propagate"
      #   named: "X-Tenant-Id"
      # - op: "propagate"
      #   named: "User-Agent"

      # # 'User-Agent': 'graphql-ws client',
      # - op: "set"
      #   name: "Content-Type"
      #   value: "application/json"

cors:
  allow_origins: ["*"]
#  allow_methods:
#    - POST
#    - GET
#    - HEAD
#    - DELETE
#    - OPTIONS
#    - PATCH
#    - PUT
  allow_headers: ["*"]
#    - Origin
#    - Content-Length
#    - Content-Type
  allow_credentials: true